### ISSUE TITLE
Unable to build a container

### ISSUE THREAD

**Issue by Archie3d** [ihcby/bika-lims-docker#1]
Exception when creating a container:
```
$ docker build -t bika/lims:0.1 .
time="2017-04-26T16:06:23+01:00" level=info msg="Unable to use system certificate pool: crypto/x509: system root pool is not available on Windows"
Sending build context to Docker daemon 4.608 kB
Step 1/12 : FROM ubuntu:14.04
 ---> 302fa07d8117
Step 2/12 : MAINTAINER Denis Karpenko <denis.karpenko@ihc.by>
 ---> Using cache
 ---> aed2af07eb1e
Step 3/12 : RUN apt-get update && apt-get install -y     openssh-server     lsof     supervisor     build-essential     python-dev     git-core     libffi-dev     libpcre3-dev     g
conf     libtool     pkg-config     zlib1g-dev     libssl-dev     libexpat1-dev     libxslt1.1     gnuplot     libpcre3     libcairo2     libpango1.0-0     libgdk-pixbuf2.0-0     li
   libxslt-dev
 ---> Using cache
 ---> f4dffe21363f
Step 4/12 : ADD https://launchpad.net/plone/4.3/4.3.7/+download/Plone-4.3.7-UnifiedInstaller.tgz /opt/bika/
Downloading [==================================================>] 37.99 MB/37.99 MB
 ---> Using cache
 ---> 082a17ac6687
Step 5/12 : RUN tar -xvf /opt/bika/Plone-4.3.7-UnifiedInstaller.tgz -C /opt/bika/
 ---> Using cache
 ---> e90457ad2bfb
Step 6/12 : RUN sudo /opt/bika/Plone-4.3.7-UnifiedInstaller/install.sh --target=/usr/local/Plone --password=adminpassword --build-python zeo
 ---> Using cache
 ---> 463846e58d0c
Step 7/12 : RUN sed -ie '/^eggs =.*/{G;s/$/    bika.lims/;}'  /usr/local/Plone/zeocluster/buildout.cfg
 ---> Using cache
 ---> e134f00b661b
Step 8/12 : RUN cd /usr/local/Plone/zeocluster && sudo -u plone_buildout bin/buildout
 ---> Running in 024e94ba3766
Uninstalling precompiler.
Uninstalling zopepy.
Uninstalling client2.
Uninstalling client1.
Updating zeoserver.
Installing client1.
/usr/local/Plone/buildout-cache/eggs/setuptools-18.3.2-py2.7.egg/pkg_resources/__init__.py:203: RuntimeWarning: You have iterated over the result of pkg_resources.parse_version. Thi
cy behavior which is inconsistent with the new version class introduced in setuptools 8.0. In most cases, conversion to a tuple is unnecessary. For comparison of versions, sort the
tances directly. If you have another use case requiring the tuple, please file a bug with the setuptools project describing that need.
  stacklevel=1,
While:
  Installing client1.
  Getting distribution for 'bika.lims'.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/usr/local/Plone/buildout-cache/eggs/zc.buildout-2.4.3-py2.7.egg/zc/buildout/buildout.py", line 1992, in main
    getattr(buildout, command)(args)
  File "/usr/local/Plone/buildout-cache/eggs/zc.buildout-2.4.3-py2.7.egg/zc/buildout/buildout.py", line 666, in install
    installed_files = self[part]._call(recipe.install)
  File "/usr/local/Plone/buildout-cache/eggs/zc.buildout-2.4.3-py2.7.egg/zc/buildout/buildout.py", line 1407, in _call
    return f()
  File "/usr/local/Plone/buildout-cache/eggs/plone.recipe.zope2instance-4.2.18-py2.7.egg/plone/recipe/zope2instance/__init__.py", line 113, in install
    installed.extend(self.install_scripts())
  File "/usr/local/Plone/buildout-cache/eggs/plone.recipe.zope2instance-4.2.18-py2.7.egg/plone/recipe/zope2instance/__init__.py", line 617, in install_scripts
    requirements, ws = self.egg.working_set(['plone.recipe.zope2instance'])
  File "/usr/local/Plone/buildout-cache/eggs/zc.recipe.egg-1.3.2-py2.7.egg/zc/recipe/egg/egg.py", line 101, in working_set
    **kw)
  File "/usr/local/Plone/buildout-cache/eggs/zc.buildout-2.4.3-py2.7.egg/zc/buildout/easy_install.py", line 848, in install
    return installer.install(specs, working_set)
  File "/usr/local/Plone/buildout-cache/eggs/zc.buildout-2.4.3-py2.7.egg/zc/buildout/easy_install.py", line 635, in install
    for_buildout_run=for_buildout_run):
  File "/usr/local/Plone/buildout-cache/eggs/zc.buildout-2.4.3-py2.7.egg/zc/buildout/easy_install.py", line 477, in _get_dist
    dist, avail = self._satisfied(requirement)
  File "/usr/local/Plone/buildout-cache/eggs/zc.buildout-2.4.3-py2.7.egg/zc/buildout/easy_install.py", line 234, in _satisfied
    return None, self._obtain(req, source)
  File "/usr/local/Plone/buildout-cache/eggs/zc.buildout-2.4.3-py2.7.egg/zc/buildout/easy_install.py", line 402, in _obtain
    if index.obtain(requirement) is None:
  File "/usr/local/Plone/buildout-cache/eggs/setuptools-18.3.2-py2.7.egg/setuptools/package_index.py", line 442, in obtain
    self.prescan()
  File "/usr/local/Plone/buildout-cache/eggs/setuptools-18.3.2-py2.7.egg/setuptools/package_index.py", line 483, in prescan
    list(map(self.scan_url, self.to_scan))
  File "/usr/local/Plone/buildout-cache/eggs/setuptools-18.3.2-py2.7.egg/setuptools/package_index.py", line 761, in scan_url
    self.process_url(url, True)
  File "/usr/local/Plone/buildout-cache/eggs/setuptools-18.3.2-py2.7.egg/setuptools/package_index.py", line 304, in process_url
    f = self.open_url(url, "Download error on %s: %%s -- Some packages may not be found!" % url)
  File "/usr/local/Plone/buildout-cache/eggs/setuptools-18.3.2-py2.7.egg/setuptools/package_index.py", line 700, in open_url
    return open_with_auth(url, self.opener)
  File "/usr/local/Plone/buildout-cache/eggs/setuptools-18.3.2-py2.7.egg/setuptools/package_index.py", line 894, in _socket_timeout
    return func(*args, **kwargs)
  File "/usr/local/Plone/buildout-cache/eggs/setuptools-18.3.2-py2.7.egg/setuptools/package_index.py", line 1007, in open_with_auth
    fp = opener(request)
  File "/usr/local/Plone/Python-2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/local/Plone/Python-2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/local/Plone/Python-2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/local/Plone/Python-2.7/lib/python2.7/urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/local/Plone/Python-2.7/lib/python2.7/urllib2.py", line 1200, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/local/Plone/Python-2.7/lib/python2.7/httplib.py", line 1132, in getresponse
    response.begin()
  File "/usr/local/Plone/Python-2.7/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Plone/Python-2.7/lib/python2.7/httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/local/Plone/Python-2.7/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
The command '/bin/sh -c cd /usr/local/Plone/zeocluster && sudo -u plone_buildout bin/buildout' returned a non-zero code: 1
```

**Comment by juangallostra** [comment]
@Archie3d  Since when Docker downloads files via the ADD keyword it automatically uncompresses them you should comment or remove line 32 of the ```Dockerfile```
```RUN tar -xvf /opt/bika/Plone-4.3.7-UnifiedInstaller.tgz -C /opt/bika/```

**Comment by MakerButt** [comment]
docker build -t bika/lims:0.1 .
[+] Building 863.1s (12/14)
 => [internal] load .dockerignore                                                                                  0.1s
 => => transferring context: 2B                                                                                    0.0s
 => [internal] load build definition from Dockerfile                                                               0.1s
 => => transferring dockerfile: 1.18kB                                                                             0.0s
 => [internal] load metadata for docker.io/library/ubuntu:14.04                                                    4.1s
 => [1/9] FROM docker.io/library/ubuntu:14.04@sha256:43cb19408de1e0ecf3ba5b5372ec98978963d6d0be42d0ad825e77a3bd1  51.3s
 => => resolve docker.io/library/ubuntu:14.04@sha256:43cb19408de1e0ecf3ba5b5372ec98978963d6d0be42d0ad825e77a3bd16  0.0s
 => => sha256:13b66b487594a1f2b75396013bc05d29d9f527852d96c5577cc4f187559875d0 3.31kB / 3.31kB                     0.0s
 => => sha256:2e6e20c8e2e69fa5c3fcc310f419975cef5fbeb6f7f2fe1374071141281b6a06 70.69MB / 70.69MB                  47.5s
 => => sha256:0551a797c01db074ab0233ceb567e66b8ebdcb9de9a2e7baa36d57dfbca463a3 72.66kB / 72.66kB                   0.8s
 => => sha256:512123a864da5e2a62949e65b67106292c5c704eff90cac2b949fc8d7ac1e58e 189B / 189B                         0.3s
 => => sha256:43cb19408de1e0ecf3ba5b5372ec98978963d6d0be42d0ad825e77a3bd16b5f7 1.20kB / 1.20kB                     0.0s
 => => sha256:881afbae521c910f764f7187dbfbca3cc10c26f8bafa458c76dda009a901c29d 945B / 945B                         0.0s
 => => extracting sha256:2e6e20c8e2e69fa5c3fcc310f419975cef5fbeb6f7f2fe1374071141281b6a06                          3.2s
 => => extracting sha256:0551a797c01db074ab0233ceb567e66b8ebdcb9de9a2e7baa36d57dfbca463a3                          0.0s
 => => extracting sha256:512123a864da5e2a62949e65b67106292c5c704eff90cac2b949fc8d7ac1e58e                          0.0s
 => https://launchpad.net/plone/4.3/4.3.7/+download/Plone-4.3.7-UnifiedInstaller.tgz                               0.0s
 => [internal] load build context                                                                                  0.0s
 => => transferring context: 640B                                                                                  0.0s
 => [2/9] RUN apt-get update && apt-get install -y     openssh-server     lsof     supervisor     build-essenti  551.0s
 => [3/9] ADD https://launchpad.net/plone/4.3/4.3.7/+download/Plone-4.3.7-UnifiedInstaller.tgz /opt/bika/          0.2s
 => [4/9] RUN tar -xvf /opt/bika/Plone-4.3.7-UnifiedInstaller.tgz -C /opt/bika/                                    0.7s
 => [5/9] RUN sudo /opt/bika/Plone-4.3.7-UnifiedInstaller/install.sh --target=/usr/local/Plone --password=admin  246.5s
 => [6/9] RUN sed -ie '/^eggs =.*/{G;s/$/    bika.lims/;}'  /usr/local/Plone/zeocluster/buildout.cfg               0.4s
 => ERROR [7/9] RUN cd /usr/local/Plone/zeocluster && sudo -u plone_buildout bin/buildout                          8.8s
------
 > [7/9] RUN cd /usr/local/Plone/zeocluster && sudo -u plone_buildout bin/buildout:
#11 1.590 Uninstalling precompiler.
#11 1.590 Uninstalling zopepy.
#11 1.591 Uninstalling client2.
#11 1.593 Uninstalling client1.
#11 1.594 Updating zeoserver.
#11 1.668 Installing client1.
#11 1.669 /usr/local/Plone/buildout-cache/eggs/setuptools-18.3.2-py2.7.egg/pkg_resources/__init__.py:203: RuntimeWarning: You have iterated over the result of pkg_resources.parse_version. This is a legacy behavior which is inconsistent with the new version class introduced in setuptools 8.0. In most cases, conversion to a tuple is unnecessary. For comparison of versions, sort the Version instances directly. If you have another use case requiring the tuple, please file a bug with the setuptools project describing that need.
#11 1.669   stacklevel=1,
#11 4.753 Download error on http://download.zope.org/ppix/: hostname 'download.zope.org' doesn't match 'vm06.plyp.com' -- Some packages may not be found!
#11 5.906 Download error on http://download.zope.org/distribution/: hostname 'download.zope.org' doesn't match 'vm06.plyp.com' -- Some packages may not be found!
#11 6.681 Download error on http://effbot.org/downloads: hostname 'effbot.org' doesn't match either of 'www.github.com', '*.github.com', 'github.com', '*.github.io', 'github.io', '*.githubusercontent.com', 'githubusercontent.com' -- Some packages may not be found!
#11 8.624 Couldn't find index page for 'bika.lims' (maybe misspelled?)
#11 8.719 Getting distribution for 'bika.lims'.
#11 8.719 Couldn't find index page for 'bika.lims' (maybe misspelled?)
#11 8.721 While:
#11 8.721   Installing client1.
#11 8.721   Getting distribution for 'bika.lims'.
#11 8.721 Error: Couldn't find a distribution for 'bika.lims'.
------
failed to solve with frontend dockerfile.v0: failed to build LLB: executor failed running [/bin/sh -c cd /usr/local/Plone/zeocluster && sudo -u plone_buildout bin/buildout]: runc did not terminate sucessfully
